[package]
name = "raast-qr-cli"
description = "CLI tool to inspect, generate, and verify Raast & EMVCo QR payloads."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
raast-qr = { path = "../raast-qr", version = "0.1.10", features = ["serde"] }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust_decimal = { workspace = true }
