[package]
name = "raast-qr"
description = "High-performance, #![no_std], fail-closed EMVCo & Raast QR engine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["std"]
std = ["alloc", "rust_decimal/std", "dep:thiserror"]
alloc = []
serde = ["dep:serde", "rust_decimal/serde-with-str"]

[dependencies]
rust_decimal = { workspace = true }
thiserror = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
rust_decimal_macros = { workspace = true }
proptest = "1.4"
